---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1xu75uw7kmue88ph23qktkn7pzvgdn45wpvkqavkfckqw4t2tpshqaexjvr
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1xu75uw7kmue88ph23qktkn7pzvgdn45wpvkqavkfckqw4t2tpshqaexjvr
