# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KmKTFSNlP2g0ZFYQx68BY10=,iv:bcjjc1RDK6slwrjvOSkiH3gf/8akQILZioBSsWo7aoM=,tag:DuTrzLM9x3ZC6I2mh3AFmg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:KvSRz6zRVFnAsV+IPIYXSp+fImfqLKq3TFjPAPL3IGCx9AL32A==,iv:0IKZb47gtBdJfM/ZDDKJxJT7h2YV8KUvkRPEpCDwsLg=,tag:WYTUjXC2Om+89sOhf9g2ew==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:GQ5nsczvsPQFKKdPczW7A9MXqg==,iv:w6HFHY3ebe8Lwh1vutgTC6xMBbO3fltYvIou9+wpS/c=,tag:445ppKJgRGP/TOsmLU6i7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xu75uw7kmue88ph23qktkn7pzvgdn45wpvkqavkfckqw4t2tpshqaexjvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQzJmZm8vYzE0ZXgva042
            SkpBK3c3ZEpPbVBSdmhPaG5jZ3dUMUhQQ1MwCjZTdG91SDYybWo4YzM1bVBWdC9a
            dnErajhwS1RocWZoMTBKV29zaEEyR0EKLS0tIG5OdWdYa3p5RVlzei94V0ltTXJX
            dlhKL2hOVFd2WnNMTXNoYUJyRzVRbjAK7euZqauYNbMnzssi++Q1tkLdgEbh11Gq
            jRvdaQaByTdkAdPHm5YqZ3LlrwvETRL+m8Fi/whJdomsJu4diujjFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T20:25:33Z"
    mac: ENC[AES256_GCM,data:fpLKttAm1DEHmOZyGOFirI/dQAkDYJEMhPcw63rhqJ7RiEpZQNwKtymOUTQu645xXx+RXJrLqrhOsixST4x0CMaHahDkpf3/HEN15Ty8cbHhkx42ia8fX3fN0UscJjFmjDNIt39FaC5BlniTCrVh102IvHEEojMGaNKbu7CfNSU=,iv:f5OsblApooWaDinXYgQQpVjSl8LhE+hj80J4G46gqWU=,tag:SvYj1nhBoz6tt4lDnTOK/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
