# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:ClJbigqO+5Qg+ckdHKrwSfU=,iv:CGHVZCK/51Y/V8AkCpjspciNEU/+QnVb4T5qZ2HxByE=,tag:Uc5ZyTHoDOEeQ0KbM4WinQ==,type:str]
    api-key: ENC[AES256_GCM,data:STL+Hsm4mGJZZsXk8PVvaYYC7B6a2ufomNPTO3fhUE9QEQMY0Q==,iv:FNPtqOiPNNa9BLV5+Yz6DwT1l3g3VSqyWkOdCRvo4UM=,tag:o9hyRQBeW2zbc+dk0oWPaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xu75uw7kmue88ph23qktkn7pzvgdn45wpvkqavkfckqw4t2tpshqaexjvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SndlcmJYYS9DNXMvT0px
            VWRnWGR1eElKOWRNcHV0QmdHcHp3MGlrVEZzCjE1REJ5WWliczV3Vlhadnk0cGpQ
            cGFSeVFaZmNlcVpMTGhkVWtFNktqUHMKLS0tIExINVlST1poTHg2TU0rUzNmcEsz
            UTBKV1BKYXlWaHp5d0Q3d3JqU0kyR2sKBv9DZozCTuXtwjf2iEEJOHy2Jw/DCFfZ
            Oo+oxnJLbMGKmL63QlOEkBvT1y99sKZCfZQDja0eA7kK163xo6zCJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T18:31:16Z"
    mac: ENC[AES256_GCM,data:qObNzNxNC5ex/siJrb75m+aOla8MCNdKwFbOrbP4z3xPtWHgPqnvWe9hRel8FjDiQDaQJ01h9dF9dMCtES4f/s5vxdj72uHF3z+6Yk3v+yAbTcJQsONjPc70eCI6ugvbN+HXzXIy1s78EOVAwbYaLAbwaEQWi+kOmiqGfU0Pi7E=,iv:1ptdvHQ2QJKiYV0AYiUqHXaylDmg8ZDFs7NoNN22jFs=,tag:nNHZTMjg2GNAXoJ/GJ4Mbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
