# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rED1sGswv0350N4SEnM=,iv:8GQWa56WJSDJIZ6jFJrgmY9rrewToxmcjYLPq0QbY5A=,tag:LDlur2MeoCZHlpFPIFx0hQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DH7qq6MJ/N23g7qrkQZKrMU=,iv:cRJj0QezZZOU4jxslYgZGzJTp8NY4hCibA3N4FDmQHA=,tag:/FNcghwvzKxfgPi7dkocgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xu75uw7kmue88ph23qktkn7pzvgdn45wpvkqavkfckqw4t2tpshqaexjvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRHVQblRBR0JBU3I3MmxY
            U3ZHeUpWTWxpejNLaTNpVkMwZ0JzRGc1dGdFCm9WVVMrbGVqaVFLdXYwd29Hdm1o
            anNTQUtmSHFPZFJjYVFqWmRyNDFoNjQKLS0tIEovUzUyTllBQVVXWDg1OGpnU1Jo
            YVJQM0ZWSVhaV1oxWjdRc0tlaFFiUGcKqsIkZw+DHN75ZTNnxkbHlmpWQnjvjXZI
            7caF7nyjpLu+qo4PUL3mCkedGlMK/maSLsEehf8VdX+zchluXTyoFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T20:27:44Z"
    mac: ENC[AES256_GCM,data:ijuF+w+Me/hvQuL6fSpahE4GDpD5yZbdAMfEmgM07B7pP39OTNFS56V+mPx3e1KmNH9FHKVRjGRH5gfOUfzAZdSiVyhliKkmNnto0N8H377qwUJ9QjnWXBCHp/E/rWrs/yYi5acC5iOnlkbpG9tJlQOQZdt9wjt6G5KAACOe+N0=,iv:4a2/V5dWw9GU0ugZ2g298V+/Hd9qoHwoRHNlgPVdFTY=,tag:3jynWyykGjPC3T661ftKMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
