---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Etc/UTC
  METALLB_LB_RANGE: 192.168.31.60-192.168.31.70
  METALLB_K8S_GATEWAY_ADDR: 192.168.31.60
  METALLB_TRAEFIK_ADDR: 192.168.31.61
