# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lpFExtvY2L0tQQVJi8U=,iv:4EXmSob4c7GDRmkxwvpay45hWemr9P4bBP2fcwWK1tc=,tag:SijSr2I4RBoHHa9Or2HdcQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:6ShGh72Ew3oRxwlo0xSUR9s=,iv:vvcGs3rIqp6Lyz/nKqJkSiHQu89L+Gf53F2B6Rn6OVs=,tag:s2xUKGcoB43V/c1qhK/17w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xu75uw7kmue88ph23qktkn7pzvgdn45wpvkqavkfckqw4t2tpshqaexjvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU2tpQTRwNURkQzdaS2J5
            N21TSW9yQzdkakRFNytUaEJzMDJPckpFa3hVCjZ1YmdLTU8vaU53dE9NZnNicG82
            dVJFZUJaL052SUI4a282WnpMRHBjYzQKLS0tIDNJN3ZBRjBqelF5Y3htci9JZG5B
            M0xmeC9OVXo1YzdyY1JEaUR0dWMrQ2sKWp1fvPqcwhYcfz+3GHCZtK9QFDiMdtrf
            8UYDkE5/hVdXLvPUua1k8aDK6MTUC11C62u/1KIt/Gm7Yr992iwxxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T18:31:16Z"
    mac: ENC[AES256_GCM,data:2StOJ/+dYIAOSZWtcxG6P0Wmtvum2DQC5LNeNMSUG8kTN50c25kQS07CuOeZm9Q9Gp6LO66gNJwRrHqA9ctJLxlqZuxNtkhF3PAskc2Yr8FTGT3alt2LwTruxTnzNYOfj21ctA2nugprOW4n68qiP3tAQug9pAd/JjY0CCSCUAQ=,iv:0e0ZPaA5JaAfglVR4FeJLv7M6Xb7dDp7EBaIHBNfsKQ=,tag:qobVujq8tb/xWpyUSzdenQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
