# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Nw1q8Po8yxg59ilIErvRb1j3rgOHTPjsF5hYYQttP6MQQSmimusYHA==,iv:z0WT1G3+AermE6OdiVzSkT7Np0UBRU7jdOTo8M1TYFM=,tag:I4X3xtSj+MTShAk2xgzEvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xu75uw7kmue88ph23qktkn7pzvgdn45wpvkqavkfckqw4t2tpshqaexjvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV2tVT1V2TzFVekc0WHZh
            cmpuRjhJR0xtVUttT1YzU2tDNFoyRmxnR0E4CmNCTGdjNzQ1NHNvOXVUOFQ3dXUw
            QW1DdmhKbC9haVZLVDVLUW1MWEovQk0KLS0tIGY5N1V2TUxzSVFUbnQ5VmtkSTl2
            SEJMWW1STjBZRXZVbXRRUUR5dGZHMzAKc2jZfG2vKYVXhQNAob1fz95OfOUjcbHG
            9OTQukvTILx/tMleJDEUBwIootyzEvchGg+nOKQuKUJRLJxs44yMqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T20:25:33Z"
    mac: ENC[AES256_GCM,data:TIadinhyza3dbiBdvSlWVlf2621hFgx6X5dDSkp2NFa35VR21324z9oCQBIy2aydkvmhoTs9zMTk5PvGYSOdKkMfjkNo5vCUuawzyeAqZbkRkYgtBM6pxnL8cpqB19x+6UzLL8nLM0byXddmpTDwF6IzbJdk/xW85NoYaoT4QI8=,iv:FMuOIpvNIVpQjpct+xhGgfuHenz+GavZv98PDit3XCs=,tag:TUmbDoYQcLQfFDnF6DM1Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
