---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iobroker
  namespace: default
  labels:
    app: iobroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iobroker
  template:
    metadata:
      labels:
        app: iobroker
    spec:
      containers:
        - name: iobroker
          image: buanet/iobroker
          ports:
            - containerPort: 8081
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: iobroker-service
  namespace: default
spec:
  selector:
    app: iobroker
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: vis
    - protocol: TCP
      port: 8081
      targetPort: 80
      name: admin
  type: LoadBalancer
